CREATE TABLE lesson4_students (
 id TEXT PRIMARY KEY,
 class_id TEXT NOT NULL CHECK (class_id IN ('601','602','603','604','605','606')),
 name TEXT NOT NULL,
 manual BOOLEAN NOT NULL DEFAULT FALSE,
 active BOOLEAN NOT NULL DEFAULT TRUE,
 position BIGINT GENERATED BY DEFAULT AS IDENTITY
);
CREATE TABLE lesson4_rounds (class_id TEXT PRIMARY KEY, n INTEGER NOT NULL DEFAULT 1 CHECK (n > 0));
INSERT INTO lesson4_rounds(class_id) VALUES ('601'),('602'),('603'),('604'),('605'),('606');
CREATE TABLE lesson4_states (sid TEXT NOT NULL REFERENCES lesson4_students(id), round TEXT NOT NULL, data JSONB NOT NULL, PRIMARY KEY(sid,round));
CREATE TABLE lesson4_sessions (token TEXT PRIMARY KEY, sid TEXT NOT NULL REFERENCES lesson4_students(id), expires BIGINT NOT NULL);
CREATE TABLE lesson4_events (id TEXT NOT NULL, sid TEXT NOT NULL REFERENCES lesson4_students(id), round TEXT NOT NULL, PRIMARY KEY(id,sid,round));
CREATE TABLE lesson4_exams (id TEXT PRIMARY KEY, sid TEXT NOT NULL REFERENCES lesson4_students(id), round TEXT NOT NULL, data JSONB NOT NULL, created TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX lesson4_exams_student_round ON lesson4_exams(sid,round,created DESC);
CREATE TABLE lesson4_live (id INTEGER PRIMARY KEY CHECK(id=1), data JSONB NOT NULL);
INSERT INTO lesson4_live VALUES (1,'{"at":null,"level":0,"lamp":false,"active":false,"triggerCount":0}');
